sudo: false
language: node_js
node_js:
  - stable
addons:
  ssh_known_hosts: 47.102.147.68
cache:
  directories:
    - node_modules
branches:
  only:
    - master # build master branch only
before_install:
  - openssl aes-256-cbc -K $encrypted_1063880fb116_key -iv $encrypted_1063880fb116_iv -in id_rsa.enc -out /tmp/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa
  - npm install -g hexo-cli
install:
  - npm install
  - npm install hexo-deployer-git --save
  - npm install hexo-deployer-rsync --save
  - npm install hexo-renderer-pug --save
  - npm install hexo-renderer-scss --save
script:
  - hexo clean
  - hexo generate # generate static files
after_success:
  - git config --global user.name "Aneureka"
  - git config --global user.email "aneureka2@gmail.com"
  - sed -i "s/github_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy
