sudo: false
language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
branches:
  only:
    - master # build master branch only
before_install:
  - openssl aes-256-cbc -K $encrypted_cd2fad4c7d8e_key -iv $encrypted_cd2fad4c7d8e_iv -in id_rsa.enc -out /tmp/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa
  - npm install -g hexo-cli
install:
  - npm install
  - npm install hexo-deployer-git --save
  - npm install hexo-deployer-rsync --save
  - npm install hexo-renderer-pug --save
  - npm install hexo-renderer-scss --save
script:
  - hexo clean
  - hexo generate # generate static files
after_success:
  - git config --global user.name "Aneureka"
  - git config --global user.email "aneureka2@gmail.com"
  - hexo deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public